# Generated by Django 4.1.3 on 2023-02-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_rename_days_details_day1'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='day2',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='details',
            name='day3',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='details',
            name='day1',
            field=models.CharField(default='', max_length=60),
        ),
    ]
