# Generated by Django 4.1.3 on 2023-02-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_alter_details_day1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='day2',
            field=models.TextField(),
        ),
    ]
