# Generated by Django 4.1.3 on 2023-02-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_alter_details_day2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='day3',
            field=models.TextField(),
        ),
    ]
